config/routes.rb
MyMvp::Application.routes.draw do

  get "comments/create"

  get "microposts/index"

  get "microposts/show"

  get "microposts/new"

  resources :sessions,   only: [:new, :create, :destroy]
  resources :basketballs
  resources :baseballs
  resources :users
	resources :identities

resources :microposts do
  resources :comments
end

  get "basketballs/new"
  get "basketballs/index"

  get "basketballs/create"

  get "basketballs/edit"
	get 'index' => "microposts#index"

 	root :to => 'sessions#signup'
	match 'microposts/' => 'microposts#index'
	match "/auth/:provider/callback" => "sessions#create"
	match "/auth/failure", to: "sessions#failure"
	match "/signout" => "sessions#destroy", :as => :signout
	match 'user_criteria/' => 'users#user_criteria'
	match 'basketball_personal/' => 'users#basketball_personal'	
	match 'basketball_stats/' => 'users#basketball_stats'	
	match 'basketball_video/' => 'users#basketball_video'	
	match 'baseball_personal/' => 'users#baseball_personal'	
	match 'baseball_stats/' => 'users#baseball_stats'	
	match 'baseball_video/' => 'users#baseball_video'
	match 'profile/' => 'users#profile'

end

app/models/baseball_profile.rb
class BaseballProfile < ActiveRecord::Base
		belongs_to :user
end

app/models/basketball.rb
class Basketball < ActiveRecord::Base
			belongs_to :user
end

app/models/basketball_profile.rb
class BasketballProfile < ActiveRecord::Base
		belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	attr_accessible :content, :user_id, :micropost_id

	belongs_to :micropost
	belongs_to :user

	validates :content, presence: true, length: {maximum: 140 }
	
  #default_scope order: 'comments.created_at DESC'

end

app/models/comment2.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :micropost

	attr_accessible :reply


	validates :reply, presence: true, length: { maximum: 140 }
	validates :user_id, presence: true

	default_scope order: 'comments,created_at DESC'

end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	attr_accessible :content
  belongs_to :user
	has_many :comments, :dependent => :destroy
	accepts_nested_attributes_for :comments
  
	validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

	

default_scope order: 'microposts.created_at DESC'


end

app/models/micropost2.rb
class Micropost < ActiveRecord::Base
	attr_accessible :content
	belongs_to :user
	has_many :comments, :dependent => :destroy
	
	accepts_nested_attributes_for :comments

	validates :user_id, presence: true
	validates :content, presence: true, length: { maximum: 140 }

	default_scope order: 'microposts.created_at DESC'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	belongs_to :main_basketball
end

app/models/user.rb
class User < ActiveRecord::Base
 include Gravtastic
	attr_accessible :role, 
									:current_team,
									:current_level,
								 :former_team,
								 :former_level,
									:sport, 
									:birthdate, 
									:ppg, 
									:rpg, 
									:apg, 
									:spg,
									:games_played,
									:minutes_per_game,
									:field_goal_made,
									:field_goal_attempt,
									:three_point_made,
									:three_point_attempt,
									:free_throw_made,
									:free_throw_attempt,
									:bpg,
									:name, 
									:email, 
									:password, 
									:password_confirmation, 
									:gender, 
									:country, 
									:bio,
									:position,
									:height,
									:weight,
									:video_url_1,
									:video_url_2,
									:video_url_3,
									:video_title

  gravtastic :email
	#has_secure_password

	has_one :basketball
	has_many :microposts, :dependent => :destroy
	has_many :comments, :dependent => :destroy
	accepts_nested_attributes_for :microposts

	def self.create_with_omniauth(auth)
  create! do |user|
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    user.name = auth["info"]["name"]
		user.email = auth["info"]["email"]
  end
end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.xml
  def index #Loops through all the profiles and renders them
    @profiles = Profile.all
  	@my_profiles = {'Visa' => 1, 'Mastercard' => 2, 'Switch' => 3}
		
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.xml
  def show #Shows the profile that was created
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.xml
  def new #Create new profile
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.xml
  def create
    @profile = Profile.new(params[:profile])
		@profile.user_id = current_user.id #fk between user and profile

    respond_to do |format|
      if @profile.save
        format.html { redirect_to(@profile, :notice => 'Profile was successfully created.') }
        format.xml  { render :xml => @profile, :status => :created, :location => @profile }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.xml
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to(@profile, :notice => 'Profile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.xml
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to(profiles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/baseballs_helper.rb
module BaseballsHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
	def facebook_image(user)
		#fb_url = "https://graph.facebook.com/#{user.uid}/picture"
		
	end	
end

app/views/profiles/_baseball.html.erb
<h1>This is the baseball profile</h1>

app/views/profiles/_basketball5.html.erb
<h1>This is the basketball profile!</h1>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
    <%= f.label :birthdate %><br />
    <%= f.date_select :birthdate %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
		<%= f.select(:title, ["Player", "Team", "Agent"]) %>
  </div>
  <div class="field">
    <%= f.label :sport %><br />
    <%= f.select(:sport, ["Basketball", "Baseball", "Football"]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>Birthdate</th>
    <th>Title</th>
    <th>Sport</th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.birthdate %></td>
    <td><%= profile.title %></td>
    <td><%= profile.sport %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<% if @profile.sport == 'Baseball' && @profile.title == 'Player' %>
<%= render :partial => 'baseball' %>
<% end %>

<p id="notice"><%= notice %></p>
<p> 
  <b>Birthdate:</b>
  <%= @profile.birthdate %>
</p>

<p>
  <b>Name:</b>
  <%= @profile.title %>
</p>

<p>
  <b>Sport:</b>
  <%= @profile.sport %>
</p>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>