config/routes.rb
MyMvp::Application.routes.draw do

  get "comments/create"

  get "microposts/index"

  get "microposts/show"

  get "microposts/new"

  resources :sessions,   only: [:new, :create, :destroy]
  resources :basketballs
  resources :baseballs
  resources :users
	resources :identities

resources :microposts do
  resources :comments
end

  get "basketballs/new"
  get "basketballs/index"

  get "basketballs/create"

  get "basketballs/edit"
	get 'index' => "microposts#index"

 	root :to => 'sessions#signup'
	match 'microposts/' => 'microposts#index'
	match "/auth/:provider/callback" => "sessions#create"
	match "/auth/failure", to: "sessions#failure"
	match "/signout" => "sessions#destroy", :as => :signout
	match 'user_criteria/' => 'users#user_criteria'
	match 'basketball_personal/' => 'users#basketball_personal'	
	match 'basketball_stats/' => 'users#basketball_stats'	
	match 'basketball_video/' => 'users#basketball_video'	
	match 'baseball_personal/' => 'users#baseball_personal'	
	match 'baseball_stats/' => 'users#baseball_stats'	
	match 'baseball_video/' => 'users#baseball_video'
	match 'profile/' => 'users#profile'

end

app/models/baseball_profile.rb
class BaseballProfile < ActiveRecord::Base
		belongs_to :user
end

app/models/basketball.rb
class Basketball < ActiveRecord::Base
			belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	attr_accessible :content, :user_id, :micropost_id

	belongs_to :micropost
	belongs_to :user

	validates :content, presence: true, length: {maximum: 140 }
	
  #default_scope order: 'comments.created_at DESC'

end

app/models/comment2.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :micropost

	attr_accessible :reply


	validates :reply, presence: true, length: { maximum: 140 }
	validates :user_id, presence: true

	default_scope order: 'comments,created_at DESC'

end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	attr_accessible :content
  belongs_to :user
	has_many :comments, :dependent => :destroy
	accepts_nested_attributes_for :comments
  
	validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

	

default_scope order: 'microposts.created_at DESC'


end

app/models/micropost2.rb
class Micropost < ActiveRecord::Base
	attr_accessible :content
	belongs_to :user
	has_many :comments, :dependent => :destroy
	
	accepts_nested_attributes_for :comments

	validates :user_id, presence: true
	validates :content, presence: true, length: { maximum: 140 }

	default_scope order: 'microposts.created_at DESC'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	belongs_to :main_basketball
end

app/models/user.rb
class User < ActiveRecord::Base
 include Gravtastic
	attr_accessible :role, 
									:current_team,
									:current_level,
								 :former_team,
								 :former_level,
									:sport, 
									:birthdate, 
									:ppg, 
									:rpg, 
									:apg, 
									:spg,
									:games_played,
									:minutes_per_game,
									:field_goal_made,
									:field_goal_attempt,
									:three_point_made,
									:three_point_attempt,
									:free_throw_made,
									:free_throw_attempt,
									:bpg,
									:name, 
									:email, 
									:password, 
									:password_confirmation, 
									:gender, 
									:country, 
									:bio,
									:position,
									:height,
									:weight,
									:video_url_1,
									:video_url_2,
									:video_url_3,
									:video_title

  gravtastic :email
	#has_secure_password

	has_one :basketball
	has_many :microposts, :dependent => :destroy
	has_many :comments, :dependent => :destroy
	accepts_nested_attributes_for :microposts

	def self.create_with_omniauth(auth)
  create! do |user|
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    user.name = auth["info"]["name"]
		user.email = auth["info"]["email"]
  end
end
end

app/controllers/microposts2_controller.rb
class MicropostsController < ApplicationController
	#before_filter :signed_in_user, only: [:create, :destroy]

	def index
		@microposts = Micropost.all
		@microposts = Micropost.paginate(page: params[:page])

 		respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @microposts }
    end
	end

	def show
		@micropost = Micropost.find(params[:id])
	end

	def new
		@micropost = Micropost.new
		3.times do 
			comment = @micropost.comments.build
	 end

		
	end

  def create
		 @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_path
    else
			flash[:notice] = "Error micropost comment: #{@micropost.errors}"
      redirect_to(@micropost)
    end

  end

  def destroy
  end


end

app/helpers/baseballs_helper.rb
module BaseballsHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
	def facebook_image(user)
		#fb_url = "https://graph.facebook.com/#{user.uid}/picture"
		
	end	
end

app/views/microposts2/_comment_fields.html.erb
<p>
  <%= f.label :reply, "Comment" %><br />
  <%= f.text_field :reply %><br />
</p>

app/views/microposts2/_error_messages.html.erb
ERROR!!

app/views/microposts2/_form.html.erb
<h2>Show Microposts!</h2>
	<%= form_for Micropost.new do |f| %>
  <%= render 'error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <%= f.fields_for :comments do |builder| %>
				<%= render "comment_fields", :f => builder %>
	<% end %>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>

<% end %>

app/views/microposts2/_micropost.html.erb
<tr>
  <td class="micropost">
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    </span>
  </td>
</tr>

app/views/microposts2/_micropost_form.html.erb
<%= form_for Micropost.new do |f| %>
  <%= render 'error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/microposts2/edit.html.erb
<h1>Microposts#edit</h1>
<p>Find me in app/views/microposts/edit.html.erb</p>

app/views/microposts2/index.html.erb
<h1>Microposts#index</h1>
<p>Find me in app/views/microposts/index.html.erb</p>



<% @microposts.each do |micropost| %>
	<%= micropost.content %><br />
	<%= render 'comments/user_comments' %></br>
<% end %>



<%= will_paginate @microposts %>

app/views/microposts2/new.html.erb
<h1>Microposts#new</h1>
<p>Find me in app/views/microposts/new.html.erb</p>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts2/show.html.erb
<%= @micropost.content %>