config/routes.rb
MyMvp::Application.routes.draw do

  get "comments/create"

  get "microposts/index"

  get "microposts/show"

  get "microposts/new"

  resources :sessions,   only: [:new, :create, :destroy]
  resources :basketballs
  resources :baseballs
  resources :users
	resources :identities

resources :microposts do
  resources :comments
end

  get "basketballs/new"
  get "basketballs/index"

  get "basketballs/create"

  get "basketballs/edit"
	get 'index' => "microposts#index"

 	root :to => 'sessions#signup'
	match 'microposts/' => 'microposts#index'
	match "/auth/:provider/callback" => "sessions#create"
	match "/auth/failure", to: "sessions#failure"
	match "/signout" => "sessions#destroy", :as => :signout
	match 'user_criteria/' => 'users#user_criteria'
	match 'basketball_personal/' => 'users#basketball_personal'	
	match 'basketball_stats/' => 'users#basketball_stats'	
	match 'basketball_video/' => 'users#basketball_video'	
	match 'baseball_personal/' => 'users#baseball_personal'	
	match 'baseball_stats/' => 'users#baseball_stats'	
	match 'baseball_video/' => 'users#baseball_video'
	match 'profile/' => 'users#profile'

end

app/models/baseball_profile.rb
class BaseballProfile < ActiveRecord::Base
		belongs_to :user
end

app/models/basketball.rb
class Basketball < ActiveRecord::Base
			belongs_to :user
end

app/models/basketball_profile.rb
class BasketballProfile < ActiveRecord::Base
		belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	attr_accessible :content, :user_id, :micropost_id

	belongs_to :micropost
	belongs_to :user

	validates :content, presence: true, length: {maximum: 140 }
	
  #default_scope order: 'comments.created_at DESC'

end

app/models/comment2.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :micropost

	attr_accessible :reply


	validates :reply, presence: true, length: { maximum: 140 }
	validates :user_id, presence: true

	default_scope order: 'comments,created_at DESC'

end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	attr_accessible :content
  belongs_to :user
	has_many :comments, :dependent => :destroy
	accepts_nested_attributes_for :comments
  
	validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

	

default_scope order: 'microposts.created_at DESC'


end

app/models/micropost2.rb
class Micropost < ActiveRecord::Base
	attr_accessible :content
	belongs_to :user
	has_many :comments, :dependent => :destroy
	
	accepts_nested_attributes_for :comments

	validates :user_id, presence: true
	validates :content, presence: true, length: { maximum: 140 }

	default_scope order: 'microposts.created_at DESC'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	belongs_to :main_basketball
end

app/models/user.rb
class User < ActiveRecord::Base
 include Gravtastic
	attr_accessible :role, 
									:current_team,
									:current_level,
								 :former_team,
								 :former_level,
									:sport, 
									:birthdate, 
									:ppg, 
									:rpg, 
									:apg, 
									:spg,
									:games_played,
									:minutes_per_game,
									:field_goal_made,
									:field_goal_attempt,
									:three_point_made,
									:three_point_attempt,
									:free_throw_made,
									:free_throw_attempt,
									:bpg,
									:name, 
									:email, 
									:password, 
									:password_confirmation, 
									:gender, 
									:country, 
									:bio,
									:position,
									:height,
									:weight,
									:video_url_1,
									:video_url_2,
									:video_url_3,
									:video_title

  gravtastic :email
	#has_secure_password

	has_one :basketball
	has_many :microposts, :dependent => :destroy
	has_many :comments, :dependent => :destroy
	accepts_nested_attributes_for :microposts

	def self.create_with_omniauth(auth)
  create! do |user|
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    user.name = auth["info"]["name"]
		user.email = auth["info"]["email"]
  end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	helper :all


	def index
		#@users = User.all
		@user = User.find(params[:id])
		#@microposts = @user.microposts.paginate(page: params[:page])
    #@title = @user.name
		#@user = User.find(current_user.id)
		
	end

	def new
		@user = User.new

   respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
   end
	
	end

	def create
		@user = User.find(params[:id])

		#@microposts = Micropost.find(params[:micropost_id])
		@microposts = @user.microposts.paginate(page: params[:page])

		@user.update_attributes(params[:user])

 		respond_to do |format|
   
		if @user.save
       format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
	end

  def edit
		 @user = User.find(current_user.id)
  end

	def show
		@user = User.find(params[:id])
		@microposts = @user.microposts.page(params[:page]).per(5)
    
		
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
	end

	def update
		@user = User.find(params[:id])

 respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
	end

	def user_criteria
		@user = User.find(current_user.id)
		@user.update_attributes(params[:user])
	end

	def basketball_personal
		@user = User.find(current_user.id)
	end

	
	def basketball_stats
		@user = User.find(current_user.id)
		@heights = ["4'8", "4'9", "4'10", "4'11", "5'0", "5'1", "5'2", "5'3", "5'4", "5'5", "5'6", "5'7", "5'8", "5'9", "5'10", "5'11", "6'0", "6'1", "6'2", "6'3", "6'4", "6'5", "6'6", "6'7", "6'8", "6'9", "6'10", "6'11", "7'0", "7'1", "7'2", "7'3", "7'4", "7'5", "7'6"]
		
	end

	
	def basketball_video
		@basketball_video = User.new
		@user = User.find(current_user.id)
	end

	def baseball_personal
		@user = User.find(current_user.id)
	end

	
	def baseball_stats
		@user = User.find(current_user.id)
	end

	def baseball_video
		@user = User.find(current_user.id)
	end

	def profile
		@user = User.find(current_user.id)
	end

end

app/helpers/baseballs_helper.rb
module BaseballsHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
	def facebook_image(user)
		#fb_url = "https://graph.facebook.com/#{user.uid}/picture"
		
	end	
end

app/views/users/_app_users.html.erb
<!-- Profile Picture -->
	<% if @micropost.user.provider == 'facebook' %> 
			<%= image_tag "http://graph.facebook.com/#{@user.uid}/picture" %>		
	<% else %>
			<%= image_tag @user.gravatar_url %>
  <% end %>

app/views/users/_basketball_links.html.erb
<div id="navigation2">
	<ul class="top-level2">
		<div class="menu">
			<li><%= link_to "Personal", basketball_personal_path %><br /></li>
			<li><%= link_to "Stats", basketball_stats_path %><br /></li>
			<li><%= link_to "Video", basketball_video_path %><br /></li>
		</div>
	</ul>
	
</div>
 
<br />

app/views/users/_basketball_profile.html.erb
<h2>Basketball profile for <%= @user.name %> </h2>
<%= form_for User.new do |f| %>

	<div class="field">
    <%= f.label :ppg %><br />
    <%= f.text_field :ppg %>
  </div>
	<div class="field">
    <%= f.label :rpg %><br />
    <%= f.text_field :rpg %>
  </div>
	<div class="field">
    <%= f.label :apg %><br />
    <%= f.text_field :apg %>
  </div>
 <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/_bstats.html.erb
<div class="backdrop4"></div>
		<div class="box4"><div class="close">x</div>
	<%= form_for (@user) do |f| %>
	<ul>
		<li style="float:left; padding-right: 10px;">
   		<h4>Season</h4>
			<%= f.select(:season, ["2011-2012", "2010-2011", "2009-2010"])  %>
		</li>
		<li style="float:left; padding-right: 10px;">
   		<h4>Team</h4>
			<%= f.select(:team, [@user.current_team, @user.former_team])  %>
		</li>
		<li style="float:left;  padding-right: 10px;">
   		<h4>GP</h4>
			<%= f.text_field :games_played, :class => 'box_stat'   %>
		</li>
		<li style="float:left;  padding-right: 10px;">
   		<h4>MPG</h4>
			<%= f.text_field :minutes_per_game, :class => 'box_stat'   %>
		</li>
		<li style="float:left;  padding-right: 10px;">
   		<h4>FGM</h4>
			<%= f.text_field :field_goal_made, :class => 'box_stat'   %>
		</li>
		<li style="float:left;  padding-right: 10px;">
   		<h4>FGA</h4>
			<%= f.text_field :field_goal_attempt, :class => 'box_stat'   %>
		</li>
		<li style="float:left;  padding-right: 10px;">
   		<h4>3PM</h4>
			<%= f.text_field :three_point_made, :class => 'box_stat'   %>
		</li>
		<li style="float:left;  padding-right: 10px;">
   		<h4>3PA</h4>
			<%= f.text_field :three_point_attempt, :class => 'box_stat'   %>
		</li>
		<li  style="float:left;  padding-right: 10px;">
   		<h4>FTM</h4>
			<%= f.text_field :free_throw_made, :class => 'box_stat'   %>
		</li>
		<li  style="float:left;   padding-right: 10px;">
   		<h4>FTA</h4>
			<%= f.text_field :free_throw_attempt, :class => 'box_stat'   %>
		</li>
		<li style="float:left;  padding-right: 10px;">
	    <h4>RPG</h4>
			<%= f.text_field :rpg, :class => 'box_stat' %>
		</li>
		<li style="float:left;  padding-right: 10px;">
    	<h4>APG</h4>
			<%= f.text_field :apg, :class => 'box_stat'  %>
		</li>
		<li style="float:left;  padding-right: 10px;">
    	<h4>SPG</h4>
			<%= f.text_field :spg, :class => 'box_stat'  %>
		</li>
		<li style="float:left;  padding-right: 10px;">
    	<h4>BPG</h4>
			<%= f.text_field :bpg, :class => 'box_stat'  %>
		</li>
		<li style="float:left;  padding-right: 10px;">
   		<h4>PPG</h4>
			<%= f.text_field :ppg, :class => 'box_stat' %>
		</li>
		<li style="margin-left: 10px;">
			<%= f.submit "Update", :class => 'btn btn_profile' %>
		</li>

	</ul>
	<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for User.new do |f| %>

	<div class="field">
    <%= f.label :birthdate %><br />
    <%= f.date_select :birthdate %>
  </div>
  <div class="field">
    <%= f.label :role %><br />
		<%= f.select(:role, ["Player", "Team", "Agent"]) %>
  </div>
  <div class="field">
    <%= f.label :sport %><br />
    <%= f.select(:sport, ["Basketball", "Baseball", "Football"]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_personal.html.erb
<h1 class="edit_personal">Edit / Personal Info</h1>
<%= form_for (@user) do |f| %>
<div class="personal2">
	<ul>
		<li>
			<h4>First & Last Name <h4>
			<%= f.text_field :name %>
		</li>
		<li>
			<h4>Birthdate<h4>
			<li>
				<%= f.date_select :birthdate, :start_year => 1960, :prompt => { :month => 'Select month', :day => 'Select day', :year => 'Select year' } %>
		</li>
		<li>	
			<h4>Gender<h4>
  		<%= f.select(:gender, ["Female", "Male"] , :prompt => {:gender => "Select gender"} ) %>
		</li>
		<li>
			<h4>Country</h4>
			<%= f.country_select :country %>
		</li>
		<li>
			<h4>Bio</h4>
		  <div class="textbio"><%= f.text_area :bio, :rows => 2 %></div>
		</li><br />
		<li>
			<%= f.submit 'Update', :class => "btn btn_profile" %>
		</li>

	</ul>
</div>


<% end %>	 

app/views/users/_player_basketball_stats.html.erb
<h1 class="edit_personal">Edit / Statistics</h1>
<%= form_for (@user) do |f| %>

<div class="personal2">
	<ul>
		<li style="float: left; padding-right: 10px;">
			<h4>Current Team <h4>
		  <%= f.text_field :current_team %>
		</li>
		<li>
			<h4>Level <h4>
		  <%= f.select(:current_level, ["Pro", "Semi Pro", "Collegiate", "High School"]) %>
		</li>
		<li style="float: left; padding-right: 10px;">
			<h4>Former Team <h4>
		  <%= f.text_field :former_team %>
		</li>
		<li>
			<h4>Level <h4>
		  <%= f.select(:former_level, ["Pro", "Semi Pro", "Collegiate", "High School"]) %>
		</li>
		<li>
			<h4>Position <h4>
		  <%= f.select(:position, ["Point Guard", "Shooting Guard", "Swing Forward", "Power Forward", "Center"]) %>
		</li>
		<li style="float:left; padding-right: 10px;">	
    	<h4>Height</h4>
			<!--<%= f.select(:height, ["6'0", "6'1", "6'2"]) %>-->


		<%= f.select :height, options_for_select(@heights), :prompt => true %>


  	</li>
		<li>	  
			 <h4>Weight</h4>
			 <%= f.text_field :weight, :class => 'level' %>
		</li>
		
		<li>
			<%= f.submit "Update", :class => 'btn btn_profile' %>
		</li>
	</ul>	
</div>

<% end %>

app/views/users/baseball_personal.html.erb
<!doctype html>
	<html lang="en">
		<head>
			<meta charset="utf-8"/>
			<title>Micropost</title>

		</head>
<body>
		<!-- Begin Intro -->
			<div id="company_intro">
				<div id="content">
					<h5>Your Profile!</h5>
				</div>
			</div>
		  <!-- End Intro -->


			<div id="section_profile" class="section_profile">
						<div id="main_body">
							<div id="header">
								<h1 class="message"></h1>
							</div>
			</div>
									
								    <td class="main">
      <h1>	  
        <%= @user.name %>
      </h1>


    </td>
   
  </tr>

</table>
			
<div>

<h1>Edit Your Baseball Personal Information!</h1>
		<%= render 'baseball_links'  %>

</div>
		
	<%= render 'personal' %>
</body>

	</html>

app/views/users/basketball_stats.html.erb
<!DOCTYPE HTML>

<html class="no-js" lang="en">
	<head>
		<meta charset="utf-8"/>
		<title>ScoutBuzz </title>
			<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" ></script>

<script type="text/javascript">
		
		$(document).ready(function() {
	
			$('.lightbox4').click(function() {
				$('.backdrop4, .box4' ).animate({'opacity':'.50'}, 300, 'linear');
			  $('.box4' ).animate({'opacity':'1.00'}, 300, 'linear');
				$('.backdrop4, .box4').css('display', 'block');
			});	

			$('.close').click(function(){
					close_box4();
				});
 
				$('.backdrop4').click(function(){
					close_box4();
				});


		});	

function close_box4()
			{
				$('.backdrop4, .box4').animate({'opacity':'0'}, 300, 'linear', function(){
					$('.backdrop4, .box4').css('display', 'none');
				});
			}


	</script>

</head>

	<body>
		<!-- BEGIN Main Header -->
		 <div class="navbar">
   		<div class="navbar-inner">
   		 <div class="container">
					<a class="brand" href="#"><%= image_tag 'logo.png'%></a>
					<ul style="margin-left: 165px; margin-top: 10px;" class="nav pull-right">
						<li>
							
						</li>

					</ul>
  		 </div>
    	</div>
    </div>
		<!-- END Main Header -->

	<%= render 'bstats' %>

		<div id="preview2" >
			
			<div class="personal"><%= render 'player_basketball_stats' %></div>
		  <%= render 'basketball_links' %>
			<a href="#" class="lightbox4" >stats</a>
		</div>
			
	</body>

</html>

app/views/users/basketball_video.html.erb
<!DOCTYPE HTML>

<html class="no-js" lang="en">
	<head>
		<meta charset="utf-8"/>
		<title>CompanyName - Worldwide Scout </title>
</head>

	<body>
		<!-- BEGIN Main Header -->
		 <div class="navbar">
   		<div class="navbar-inner">
   		 <div class="container">
					<a class="brand" href="#"><%= image_tag 'logo.png'%></a>
					<ul style="margin-left: 165px; margin-top: 10px;" class="nav pull-right">
						<li>
							
						</li>

					</ul>
  		 </div>
    	</div>
    </div>
		<!-- END Main Header -->

		<div id="preview2" >
			
		 <div class="personal"><%= render 'video' %></div>
		 <%= render 'basketball_links'  %>
	
		</div>
			
	</body>

</html>

app/views/users/edit.html.erb
<h1>Edit Profile for: <%= @user.name %></h1>

<% if @user.sport == 'Basketball' && @user.role == 'Player' %>
		<%= render 'basketball_links'  %>
<% end %>

app/views/users/index.html.erb
<h1>Profile for <%= user.name %></h1>

app/views/users/show.html.erb
<!DOCTYPE HTML>

<html class="no-js" lang="en">
	<head>
		<meta charset="utf-8"/>
		<title>ScoutBuzz </title>

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" ></script>

<script type="text/javascript">
		
		$(document).ready(function() {
	
			$('.lightbox5').click(function() {
				$('.backdrop5, .box5' ).animate({'opacity':'.50'}, 300, 'linear');
			  $('.box5' ).animate({'opacity':'1.00'}, 300, 'linear');
				$('.backdrop5, .box5').css('display', 'block');
			});	

			$('.close').click(function(){
					close_box5();
				});
 
				$('.backdrop5').click(function(){
					close_box5();
				});


		});	

function close_box5()
			{
				$('.backdrop5, .box5').animate({'opacity':'0'}, 300, 'linear', function(){
					$('.backdrop5, .box5').css('display', 'none');
				});
			}


	</script>
	</head>

	<body>
		<!-- BEGIN Main Header -->
		 <div class="navbar">
   		<div class="navbar-inner">
   		 <div class="container">
					<a class="brand" href="#"><%= image_tag 'logo.png'%></a>
					<ul style="margin-left: 165px; margin-top: 10px;" class="nav pull-right">
						<li>
							
						</li>

					</ul>
  		 </div>
    	</div>
    </div>
		<!-- END Main Header -->

		<div id="preview2" >
		
			 <h1>	  
        <%= @user.name %>
       </h1>


<!-- Profile Picture -->

<%= image_tag avatar_url(@user), :size => '125x150' %>

		<div class="nippleBox">
			<div class="bar">
					<h4>Microposts (<%= @user.microposts.count %>)</h4>
			</div>
				<% if	@user.microposts.any? %>
		
        	<div class="content"><%= render 'microposts/micropost' %></div>

				<% end %>


				<!--<div style="margin-left: 220px; margin-top: 200px;"><%= paginate @microposts  %></div>-->

   
		</div>

<div class="view_edit">
	<% if @user.sport == 'Basketball' && @user.role == 'Player' %>
		<%= link_to "Edit My Profile", basketball_personal_path %> |
	<a href="#" class="lightbox5">View My Profile</a>

		<div class="backdrop5"></div>
		<div class="box5"><div class="close">x</div>
		<ul>
			<li>
				<h1><%= @user.name %></h1>
			</li>
			<li style="float:left;">
				<% if @user.provider == 'facebook' %> 
					<%= image_tag "http://graph.facebook.com/#{@user.uid}/picture", :size => '230x270'  %>		
				<% end %>
		</li>
	</ul>

	<ul id="profile_intro">
		<li style="font-size: 18px;"><%= @user.position %> | <%= @user.height %>, <%= @user.weight %> | <%= @user.country %></li><hr style="width: 350px;" />
		<li><strong style="padding-right: 65px;">Sport</strong><%= @user.sport %>,<%= @user.gender %></li>
		<li><strong style="padding-right: 65px;">Born</strong> <%= @user.birthdate %></li>
		<li><strong style="padding-right: 12px;">Current Team</strong><%= @user.current_team %>, <%= @user.current_level %></li>
		<li><strong style="padding-right: 15px;">Former Team</strong><%= @user.former_team %>, <%= @user.former_level %></li>
	</ul> 

<h3 class="vid">Recent Videos</h3>
	<ul id="profile_videos" >
		<li style="float: left; padding-left: 20px; padding-right: 10px;">
			<% if @user.video_url_1.blank? %>
	
			<% else %>
				<% aha = UnvlogIt.new(@user.video_url_1) %>
			  <%= aha.embed_html(215, 190).html_safe  %>
			<% end %>
		</li>

		<li style="float: left; padding-right: 10px;">
			<% if @user.video_url_2.blank? %>
	
			<% else %>
				<% aha = UnvlogIt.new(@user.video_url_2) %>
			  <%= aha.embed_html(215, 190).html_safe  %>
			<% end %>
		</li>

			<li style="float: left;">
			<% if @user.video_url_3.blank? %>
	
			<% else %>
				<% aha = UnvlogIt.new(@user.video_url_3) %>
			  <%= aha.embed_html(215, 190).html_safe  %>
			<% end %>
		</li>

	</ul>

		<ul id="profile_player" style="width: 720px;">
				<li style="background-color: #424242; color:#ffffff; text-align: center; height: 30px;">Stats</li>
				<li style="float:left; padding-left: 10px; padding-right: 23px; background-color: #D8D8D8; height: 30px;">
					<h6 style="color: #2E2E2E;">GP</h6>				
					<%= @user.games_played %>
				</li>		
				<li style="float:left; padding-right: 15px; background-color: #D8D8D8; height: 30px;">
					<h6 style="color: #2E2E2E;">MPG</h6>
					<%= @user.minutes_per_game %>
				</li>		
				<li style="float:left; padding-right: 15px; background-color: #D8D8D8; height: 30px;">
					<h6 style="color: #2E2E2E;">FGM</h6>
					<%= @user.field_goal_made %>
				</li>		
				<li style="float:left; padding-right: 15px; background-color: #D8D8D8; height: 30px;">
					<h6 style="color: #2E2E2E;">FGA</h6>
					<%= @user.field_goal_attempt %>
				</li>
				<li style="float:left; padding-right: 15px; background-color: #D8D8D8; height: 30px;"> 
					<h6 style="color: #2E2E2E;">FG%</h6>
					<% @fgm =  @user.field_goal_made %>
					<% @fga = @user.field_goal_attempt %>		
					<!--<%= number_to_percentage(@fgm.to_f / @fga.to_f) %>-->
				</li>
				<li style="float:left; padding-right: 15px; background-color: #D8D8D8; height: 30px;">
					<h6 style="color: #2E2E2E;">3PM</h6>
					<%= @user.three_point_made %>
				</li>
				<li style="float:left; padding-right: 15px; background-color: #D8D8D8; height: 30px;">
					<h6 style="color: #2E2E2E;">3PA</h6>
					<%= @user.three_point_attempt %>
				</li>
				<li style="float:left; padding-right: 15px; background-color: #D8D8D8; height: 30px;">
					<h6 style="color: #2E2E2E;">3P%</h6>
					
				</li>
				<li style="float:left; padding-right: 15px; background-color: #D8D8D8; height: 30px;">
					<h6 style="color: #2E2E2E;">FTM</h6>
					<%= @user.free_throw_made %>
				</li>
				<li style="float:left; padding-right: 15px; background-color: #D8D8D8; height: 30px;">
					<h6 style="color: #2E2E2E;">FTA</h6>
					<%= @user.free_throw_attempt %>
				</li>	
				<li style="float:left; padding-right: 15px; background-color: #D8D8D8; height: 30px;">
					<h6 style="color: #2E2E2E;">FT%</h6>
					
				</li>
				<li style="float:left; padding-right: 15px; background-color: #D8D8D8; height: 30px;">
					<h6 style="color: #2E2E2E;">RPG</h6>
					<%= @user.rpg %>
				</li>
				<li style="float:left; padding-right: 15px; background-color: #D8D8D8; height: 30px;">
					<h6 style="color: #2E2E2E;">APG</h6>
					<%= @user.apg %>
				</li>
				<li style="float:left; padding-right: 15px; background-color: #D8D8D8; height: 30px;">
					<h6 style="color: #2E2E2E;">BLKPG</h6>
					<%= @user.bpg %>
				</li>
				<li style="float:left; padding-right: 15px; background-color: #D8D8D8; height: 30px;">
					<h6 style="color: #2E2E2E;">SPG</h6>
					<%= @user.spg %>
				</li>
				<li style="float:left; padding-right: 10px; background-color: #D8D8D8; height: 30px;">
					<h6 style="color: #2E2E2E;">PPG</h6>
					<%= @user.ppg %>
				</li>
		</ul>
		</div>
	<% end %>
	
<% if @user.sport == 'Baseball' && @user.role == 'Player' %>
		<%= link_to "Edit My Profile", baseball_personal_path %>
<% end %>

</div>
	
</div>
	</body>

</html>

app/views/users/user_criteria.html.erb
<!DOCTYPE HTML>

<html class="no-js" lang="en">
	<head>
		<meta charset="utf-8"/>
		<title>CompanyName - Worldwide Scout </title>
	</head>
	
 <body>
		<!-- BEGIN Main Header -->
		 <div class="navbar">
   		<div class="navbar-inner">
   		 <div class="container">
					<a class="brand" href="#"><%= image_tag 'logo.png'%></a>
					<ul style="margin-left: 165px; margin-top: 10px;" class="nav pull-right">
						<li>
							
						</li>

					</ul>
  		 </div>
    	</div>
    </div>
		<!-- END Main Header -->
	
			<%= render 'criteria' %>

	</body>

</html>