config/routes.rb
MyMvp::Application.routes.draw do

  get "comments/create"

  get "microposts/index"

  get "microposts/show"

  get "microposts/new"

  resources :sessions,   only: [:new, :create, :destroy]
  resources :basketballs
  resources :baseballs
  resources :users
	resources :identities

resources :microposts do
  resources :comments
end

  get "basketballs/new"
  get "basketballs/index"

  get "basketballs/create"

  get "basketballs/edit"
	get 'index' => "microposts#index"

 	root :to => 'sessions#signup'
	match 'microposts/' => 'microposts#index'
	match "/auth/:provider/callback" => "sessions#create"
	match "/auth/failure", to: "sessions#failure"
	match "/signout" => "sessions#destroy", :as => :signout
	match 'user_criteria/' => 'users#user_criteria'
	match 'basketball_personal/' => 'users#basketball_personal'	
	match 'basketball_stats/' => 'users#basketball_stats'	
	match 'basketball_video/' => 'users#basketball_video'	
	match 'baseball_personal/' => 'users#baseball_personal'	
	match 'baseball_stats/' => 'users#baseball_stats'	
	match 'baseball_video/' => 'users#baseball_video'
	match 'profile/' => 'users#profile'

end

app/models/baseball_profile.rb
class BaseballProfile < ActiveRecord::Base
		belongs_to :user
end

app/models/basketball.rb
class Basketball < ActiveRecord::Base
			belongs_to :user
end

app/models/basketball_profile.rb
class BasketballProfile < ActiveRecord::Base
		belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	attr_accessible :content, :user_id, :micropost_id

	belongs_to :micropost
	belongs_to :user

	validates :content, presence: true, length: {maximum: 140 }
	
  #default_scope order: 'comments.created_at DESC'

end

app/models/comment2.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :micropost

	attr_accessible :reply


	validates :reply, presence: true, length: { maximum: 140 }
	validates :user_id, presence: true

	default_scope order: 'comments,created_at DESC'

end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	attr_accessible :content
  belongs_to :user
	has_many :comments, :dependent => :destroy
	accepts_nested_attributes_for :comments
  
	validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

	

default_scope order: 'microposts.created_at DESC'


end

app/models/micropost2.rb
class Micropost < ActiveRecord::Base
	attr_accessible :content
	belongs_to :user
	has_many :comments, :dependent => :destroy
	
	accepts_nested_attributes_for :comments

	validates :user_id, presence: true
	validates :content, presence: true, length: { maximum: 140 }

	default_scope order: 'microposts.created_at DESC'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	belongs_to :main_basketball
end

app/models/user.rb
class User < ActiveRecord::Base
 include Gravtastic
	attr_accessible :role, 
									:current_team,
									:current_level,
								 :former_team,
								 :former_level,
									:sport, 
									:birthdate, 
									:ppg, 
									:rpg, 
									:apg, 
									:spg,
									:games_played,
									:minutes_per_game,
									:field_goal_made,
									:field_goal_attempt,
									:three_point_made,
									:three_point_attempt,
									:free_throw_made,
									:free_throw_attempt,
									:bpg,
									:name, 
									:email, 
									:password, 
									:password_confirmation, 
									:gender, 
									:country, 
									:bio,
									:position,
									:height,
									:weight,
									:video_url_1,
									:video_url_2,
									:video_url_3,
									:video_title

  gravtastic :email
	#has_secure_password

	has_one :basketball
	has_many :microposts, :dependent => :destroy
	has_many :comments, :dependent => :destroy
	accepts_nested_attributes_for :microposts

	def self.create_with_omniauth(auth)
  create! do |user|
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    user.name = auth["info"]["name"]
		user.email = auth["info"]["email"]
  end
end
end

app/controllers/basketball_profiles_controller.rb
class BasketballProfilesController < ApplicationController
  # GET /basketball_profiles
  # GET /basketball_profiles.xml
  def index
    @basketball_profiles = BasketballProfile.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @basketball_profiles }
    end
  end

  # GET /basketball_profiles/1
  # GET /basketball_profiles/1.xml
  def show
    @basketball_profile = BasketballProfile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @basketball_profile }
    end
  end

  # GET /basketball_profiles/new
  # GET /basketball_profiles/new.xml
  def new
    @basketball_profile = BasketballProfile.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @basketball_profile }
    end
  end

  # GET /basketball_profiles/1/edit
  def edit
    @basketball_profile = BasketballProfile.find(params[:id])
  end

  # POST /basketball_profiles
  # POST /basketball_profiles.xml
  def create
    @basketball_profile = BasketballProfile.new(params[:basketball_profile])
		@basketball_profile.user_id = current_user.id

    respond_to do |format|
      if @basketball_profile.save
        format.html { redirect_to(@basketball_profile, :notice => 'Basketball profile was successfully created.') }
        format.xml  { render :xml => @basketball_profile, :status => :created, :location => @basketball_profile }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @basketball_profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /basketball_profiles/1
  # PUT /basketball_profiles/1.xml
  def update
    @basketball_profile = BasketballProfile.find(params[:id])

    respond_to do |format|
      if @basketball_profile.update_attributes(params[:basketball_profile])
        format.html { redirect_to(@basketball_profile, :notice => 'Basketball profile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @basketball_profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /basketball_profiles/1
  # DELETE /basketball_profiles/1.xml
  def destroy
    @basketball_profile = BasketballProfile.find(params[:id])
    @basketball_profile.destroy

    respond_to do |format|
      format.html { redirect_to(basketball_profiles_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/baseballs_helper.rb
module BaseballsHelper
end

app/helpers/basketball_profiles_helper.rb
module BasketballProfilesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
	def facebook_image(user)
		#fb_url = "https://graph.facebook.com/#{user.uid}/picture"
		
	end	
end

app/views/basketball_profiles/_form.html.erb
<%= form_for BasketballProfile.new do |f| %>
  

  <div class="field">
    <%= f.label :ppg %><br />
    <%= f.text_field :ppg %>
  </div>
  <div class="field">
    <%= f.label :rpg %><br />
    <%= f.text_field :rpg %>
  </div>
  <div class="field">
    <%= f.label :apg %><br />
    <%= f.text_field :apg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/basketball_profiles/basketbally.html.erb
<%= form_for(@basketball_profile) do |f| %>
  <% if @basketball_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@basketball_profile.errors.count, "error") %> prohibited this basketball_profile from being saved:</h2>

      <ul>
      <% @basketball_profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ppg %><br />
    <%= f.text_field :ppg %>
  </div>
  <div class="field">
    <%= f.label :rpg %><br />
    <%= f.text_field :rpg %>
  </div>
  <div class="field">
    <%= f.label :apg %><br />
    <%= f.text_field :apg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/basketball_profiles/edit.html.erb
<h1>Editing basketball_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @basketball_profile %> |
<%= link_to 'Back', basketball_profiles_path %>

app/views/basketball_profiles/index.html.erb
<h1>Listing basketball_profiles</h1>

<table>
  <tr>
    <th>Ppg</th>
    <th>Rpg</th>
    <th>Apg</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @basketball_profiles.each do |basketball_profile| %>
  <tr>
    <td><%= basketball_profile.ppg %></td>
    <td><%= basketball_profile.rpg %></td>
    <td><%= basketball_profile.apg %></td>
    <td><%= link_to 'Show', basketball_profile %></td>
    <td><%= link_to 'Edit', edit_basketball_profile_path(basketball_profile) %></td>
    <td><%= link_to 'Destroy', basketball_profile, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Basketball profile', new_basketball_profile_path %>

app/views/basketball_profiles/new.html.erb
<h1>New basketball_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', basketball_profiles_path %>

app/views/basketball_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ppg:</b>
  <%= @basketball_profile.ppg %>
</p>

<p>
  <b>Rpg:</b>
  <%= @basketball_profile.rpg %>
</p>

<p>
  <b>Apg:</b>
  <%= @basketball_profile.apg %>
</p>


<%= link_to 'Edit', edit_basketball_profile_path(@basketball_profile) %> |
<%= link_to 'Back', basketball_profiles_path %>